name: "Commit and push changes"
description: "Commit specified files to the current PR branch"
inputs:
  file:
    description: "File or directory to add to git"
    required: true
  message:
    description: "Commit message"
    default: "chore: automated update"

runs:
  using: "composite"
  steps:
    - name: Commit changes
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${{ inputs.file }}"
        if ! git diff --cached --quiet; then
          git commit -m "${{ inputs.message }}"
          git push origin HEAD:${{ github.head_ref }}
        else
          echo "ℹ️ No changes to commit."
        fi
