name: Check JSON and TOML format

on:
  pull_request:
    paths:
      - '**/*.json'
      - '**/*.toml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install toml tomli

      - name: Validate JSON files
        run: |
          echo "Checking JSON files..."
          find . -name "*.json" | while read file; do
            echo "Validating $file"
            python -m json.tool "$file" > /dev/null || {
              echo "❌ Invalid JSON: $file"
              exit 1
            }
          done

      - name: Validate TOML files
        run: |
          echo "Checking TOML files..."
          find . -name "*.toml" | while read file; do
            echo "Validating $file"
            python -c "import tomli; tomli.load(open('$file', 'rb'))" || {
              echo "❌ Invalid TOML: $file"
              exit 1
            }
          done
