name: Update Whisker Icons

permissions:
  contents: write

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'whisker/icons/**'
      - 'scripts/**'
      - '.github/workflows/whisker-icons-version.yml'

jobs:
  update-whisker-icons:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install toml

      - name: Check for icon changes
        id: changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

          # 获取 PR 中改动的文件
          changed_files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)

          echo "Changed files:"
          echo "$changed_files"

          mkdir -p changed
          echo "$changed_files" | grep '^whisker/icons/' > changed/icons.txt || true

          if [ -s changed/icons.txt ]; then
            echo "ICON_CHANGED=true" >> "$GITHUB_ENV"
          else
            echo "No icon changes found."
            echo "ICON_CHANGED=false" >> "$GITHUB_ENV"
          fi

      - name: Bump icon version and generate JSON
        if: env.ICON_CHANGED == 'true'
        run: |
          python whisker/scripts/bump_icon_version.py

      - name: Commit and push changes of icons
        if: env.ICON_CHANGED == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add whisker/configs.toml whisker/versions/icons/changes/*.json
          git commit -m "chore: bump icon version and generate changelog" || echo "Nothing to commit"
          git push origin HEAD:${{ github.head_ref }}
          
      - name: Generate versions/icons/all.json
        run: python whisker/scripts/generate_all_icons.py

      - name: Commit and push versions/icons/all.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add whisker/versions/icons/all.json
          git commit -m "chore: regenerate versions/icons/all.json with all icons" || echo "Nothing to commit"
          git push origin HEAD:${{ github.head_ref }}

      - name: Generate words_step_1.json
        run: python whisker/scripts/generate_words_step_1.py

      - name: Commit words_step_1.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add whisker/versions/words/words_step_1.json
          git commit -m "chore: generate words_step_1.json" || echo "Nothing to commit"
          git push origin HEAD:${{ github.head_ref }}